### ISSUE TITLE
Can't authenticate trow tutum node package

### ISSUE THREAD

**Issue by oscarruesga** [thenativeweb/tutum#6]
Using de 0.2.2 version of module I can't authenticate in the API.
```javascript
var Tutum = require('tutum');

var tutum = new Tutum({
  username: __MY_USERNAME__,
  apiKey: __MY_KEY__
});

tutum.post('service', {
  image: 'tutum/hello-world'
}, function (err, res) {
  if (err) {
    throw err;
  }
  console.log(res);
});

```

This is because in ./lib/tutum.js (line 43) `.set('Authorization', 'ApiKey ' + this.configuration.authorization)` it's not valid.

I replaced by:
```
.set('Authorization', 'Basic ' + new Buffer(this.configuration.authorization).toString('base64'))
```
and works well.

It's possible to fix in the master branch?

Thanks

**Comment by goloroden** [comment]
To be honest, this is already fixed in the `master` branch, unfortunately I just did not have any time yet to publish a new version to npm.

Sorry for that, and I will do it soon :-)

**Comment by goloroden** [comment]
Just tried it, but I'm having some issues with publishing to npm, since we've recently switched to an org account there.

Once we get it running, I will publish the module. Until then you may use the reference to the GitHub repo directly.

**Comment by goloroden** [comment]
Finally, it worked ... tutum@0.3.0 is on npm.
